version: '3'


services:
  postgres_db:
    image: postgres:latest
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: voucher_api
    volumes:
         - ./scripts/postgres:/docker-entrypoint-initdb.d/

  adminer:
    image: adminer
    restart: always
    depends_on:
      - postgres_db
    ports:
      - 8080:8080